name: Deploy to vercel on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dkershner6/vercel-set-env-action@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          projectName: surveyhub
          envVariableKeys: MONGODB_URI,ACCESS_CODE,SOLANA_SECRET_KEY,SOLANA_PUBLIC_KEY
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          TARGET_MONGODB_URI: preview,development,production
          TYPE_MONGODB_URI: encrypted

          ACCESS_CODE: ${{ secrets.ACCESS_CODE }}
          TARGET_ACCESS_CODE: preview,development,production
          TYPE_ACCESS_CODE: encrypted

          SOLANA_SECRET_KEY: ${{ secrets.SOLANA_SECRET_KEY }}
          TARGET_SOLANA_SECRET_KEY: preview,development,production
          TYPE_SOLANA_SECRET_KEY: encrypted

          SOLANA_PUBLIC_KEY: ${{ secrets.SOLANA_PUBLIC_KEY }}
          TARGET_SOLANA_PUBLIC_KEY: preview,development,production
          TYPE_SOLANA_PUBLIC_KEY: encrypted

      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
